### PR TITLE
Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by sjinks**

### CODE REVIEW

**Comment by sjinks** [comment]
CircleCI fails because I removed its configuration file.

After this PR gets merged, we need to deactivate the project in CircleCI.

**Comment by chriszarate** [comment]
Since this repo is a template repo for customer sites, we've intentionally provided a CircleCI config that customer sites can use once they are provisioned.

**Comment by sjinks** [comment]
Restored CircleCI config.

**Comment by mjangda** [comment]
@chriszarate would you prefer that we just leave it this with Circle CI enabled (and skip GitHub Actions here)? I think that makes more sense that switching and leaving the Circle CI configs purely as a reference / starting point.

**Comment by chriszarate** [comment]
> @chriszarate would you prefer that we just leave it this with Circle CI enabled (and skip GitHub Actions here)? I think that makes more sense that switching and leaving the Circle CI configs purely as a reference / starting point.

I think so, yes. Closing with appreciation for @sjinks wrangling all of these changes! ❤️

**Pull request closed without merging**
